function [T01,T12,T23,T34,T45,T56] = MGD_ur10(q1,q2,q3,q4,q5,q6,d1,a2,a3,d4,d5,d6,pi)
%MGD_ur10
%    [T01,T12,T23,T34,T45,T56] = MGD_ur10(Q1,Q2,Q3,Q4,Q5,Q6,D1,A2,A3,D4,D5,D6,PI)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Nov-2021 10:50:02

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = cos(q6);
t8 = sin(q1);
t9 = sin(q2);
t10 = sin(q3);
t11 = sin(q4);
t12 = sin(q5);
t13 = sin(q6);
t14 = pi./2.0;
t15 = cos(t14);
t16 = sin(t14);
T01 = reshape([t2,t8,0.0,0.0,-t8.*t15,t2.*t15,t16,0.0,t8.*t16,-t2.*t16,t15,0.0,0.0,0.0,d1,1.0],[4,4]);
if nargout > 1
    T12 = reshape([t3,t9,0.0,0.0,-t9,t3,0.0,0.0,0.0,0.0,1.0,0.0,a2.*t3,a2.*t9,0.0,1.0],[4,4]);
end
if nargout > 2
    T23 = reshape([t4,t10,0.0,0.0,-t10,t4,0.0,0.0,0.0,0.0,1.0,0.0,a3.*t4,a3.*t10,0.0,1.0],[4,4]);
end
if nargout > 3
    T34 = reshape([t5,t11,0.0,0.0,-t11.*t15,t5.*t15,t16,0.0,t11.*t16,-t5.*t16,t15,0.0,0.0,0.0,d4,1.0],[4,4]);
end
if nargout > 4
    T45 = reshape([t6,t12,0.0,0.0,-t12.*t15,t6.*t15,t16,0.0,t12.*t16,-t6.*t16,t15,0.0,0.0,0.0,d5,1.0],[4,4]);
end
if nargout > 5
    T56 = reshape([t7,t13,0.0,0.0,-t13,t7,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,d6,1.0],[4,4]);
end
