function [x0T1,x1T2,x2T3] = MGDrobot(th1,th2,th3,d1,a2,a3)
%MGDrobot
%    [x0T1,x1T2,x2T3] = MGDrobot(TH1,TH2,TH3,D1,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Nov-2021 16:53:11

t2 = cos(th1);
t3 = cos(th2);
t4 = cos(th3);
t5 = sin(th1);
x0T1 = reshape([t2,t5,0.0,0.0,0.0,0.0,-1.0,0.0,-t5,t2,0.0,0.0,0.0,0.0,d1,1.0],[4,4]);
if nargout > 1
    t6 = sin(th2);
    x1T2 = reshape([t3,t6,0.0,0.0,-t6,t3,0.0,0.0,0.0,0.0,1.0,0.0,a2.*t3,a2.*t6,0.0,1.0],[4,4]);
end
if nargout > 2
    t7 = sin(th3);
    x2T3 = reshape([t4,t7,0.0,0.0,-t7,t4,0.0,0.0,0.0,0.0,1.0,0.0,a3.*t4,a3.*t7,0.0,1.0],[4,4]);
end
